var stubParams = {
    "id": "WNZP",
    "startProgram": ["WinZip.exe", "WinZip32.exe", "WinZip64.exe"],
    "shortcut": "Continue WinZip Installation.lnk",
    "mui": {
        "en": {
            "productName": "WinZip",
            "privacyPolicy": "Privacy Policy",
            "termsOfUse": "Terms of Use",
            "welcomeDescriptionTitle": "Welcome to WinZip",
            "welcomeDescription": "The easiest way to zip, protect and share your files.",
            "agreementDescriptionTitle": "License Agreement",
            "agreementDescription": "Please read the following License Agreement.",
            "agreementDescriptionEULA": "WinZip will register the acceptance of the following terms for individual end users, who install WinZip for personal use, when clicking agree on this screen.",
            "endUserLicenseAgreement": "End User License Agreement",
            "agreementDescriptionBULA": "WinZip will register the acceptance of the following terms for users, who are acting for a business and click agree on this screen.",
            "businessUserLicenseAgreement": "Business User License Agreement",
            "agreementFaq": "EULA & BULA FAQ",
            "analyticsDescriptionTitle": "WinZip Analytics",
            "analyticsDescription": "Please read the following Privacy Policy.",
            "analyticsHelpImproveDescription": "Help WinZip improve its products and services by providing anonymous usage analytics data from your WinZip after installation. You can change this decision later in Settings.",
            "analyticsCollectedDescription": "All data collected is collected using privacy-preserving techniques.",
            "agreeButtonText": "Agree",
            "doNotSendButtonText": "Do Not Send",
            "installingProgressBarText": "Installing",
            "installingDescriptionTitle": "Installing Status",
            "installDescription": "Please wait while the installer wizard downloads and optimizes the necessary packages.",
            "finishDescriptionTitle": "Thank you for installing WinZip",
            "finishDescription": "The easiest way to zip, protect and share your files",
            "nextButtonText": "Next",
            "finishButtonText": "Finish",
            "errorMessageText": "We encountered a problem while installing.  Please contact Technical Support and mention error code %d",
            "retryMessageText": "Another installation is already in progress. Complete that installation before proceeding with this install.",
            "priviledgeMessageText": "You do not have sufficient privileges to complete this installation. Log on as administrator and retry this installation.",
            "diskfullMessageText": "There is not enough space on the disk.",
            "warningText": "Warning",
            "errorText": "Error",
            "osRequirements": "WinZip requires Windows version 10.0.17134 or higher to install. Please upgrade your Windows installation.",
            "dotNetRequirements": "WinZip requires Microsoft .NET Framework 4.0 or higher. Click Next to upgrade to .NET 4.6 and continue to install WinZip.",
            "dotNet35Requirements": "WinZip requires .net 3.5 or higher. Please upgrade to .net 3.5 or higher and retry this installation.",
            "ieRequirements": "WinZip requires IE8 or higher. Please upgrade to IE8 or higher and retry this installation.",
            "outOfText": " out of ",
            "installLabel" : "installing...",
            "downloadingWinZip" : "Downloading WinZip",
            "downloadingDotNet" : "Downloading .NET Framework",
            "noNetwork" : "No network or proxy internet connection available.",
            "webview2InstallFail" : "The installation of the Microsoft WebView2 library failed. Please try installing WinZip again.",
            "osBitRequirements" : "This version of Windows does not support deploying 64-bit packages."
        },
        "fr": {
            "productName": "WinZip",
            "privacyPolicy": "Déclaration de confidentialité",
            "termsOfUse": "Conditions d'utilisation",
            "welcomeDescriptionTitle": "Bienvenue dans WinZip",
            "welcomeDescription": "La méthode la plus facile pour compresser, protéger et partager vos fichiers.",
            "agreementDescriptionTitle": "Contrat de licence",
            "agreementDescription": "Veuillez lire le contrat de licence suivant.",
            "agreementDescriptionEULA": "WinZip enregistrera l'acceptation des conditions suivantes pour les utilisateurs finaux individuels, qui installent WinZip pour un usage personnel, en cliquant sur accepter sur cet écran.",
            "endUserLicenseAgreement": "Contrat de licence utilisateur final",
            "agreementDescriptionBULA": "WinZip enregistrera l'acceptation des conditions suivantes pour les utilisateurs qui agissent pour une entreprise et qui cliquent sur accepter sur cet écran.",
            "businessUserLicenseAgreement": "Contrat de licence utilisateur professionnel",
            "agreementFaq": "FAQ CLUF & BULA",
            "analyticsDescriptionTitle": "Analyse WinZip",
            "analyticsDescription": "Veuillez lire la politique de confidentialité suivante.",
            "analyticsHelpImproveDescription": "Aidez WinZip à améliorer ses produits et services en fournissant des données d'analyse d'utilisation anonymes à partir de votre WinZip après l'installation. Vous pouvez modifier cette décision ultérieurement dans les paramètres.",
            "analyticsCollectedDescription": "Toutes les données collectées sont collectées à l'aide de techniques de protection de la vie privée.",
            "agreeButtonText": "D'accord",
            "doNotSendButtonText": "Ne pas envoyer",
            "installingProgressBarText": "Installation",
            "installingDescriptionTitle": "État de l'installation",
            "installDescription": "Veuillez patienter pendant que l'assistant d'installation télécharge et optimise les paquetages nécessaires.",
            "finishDescriptionTitle": "Merci d'avoir installé WinZip",
            "finishDescription": "La méthode la plus facile pour compresser, protéger et partager vos fichiers.",
            "nextButtonText": "Suivant",
            "finishButtonText": "Terminer",
            "errorMessageText": "Un problème est survenu pendant l'installation. Veuillez contacter l'assistance technique en indiquant le code d'erreur %d",
            "retryMessageText": "Une autre installation est déjà en cours. Terminez d'abord cette installation avant d'en relancer une nouvelle.",
            "priviledgeMessageText": "Vous ne disposez pas des droits suffisants pour effectuer cette installation. Connectez-vous en tant qu'administrateur et réessayez.",
            "osRequirements": "WinZip nécessite la version 10.0.17134 de Windows ou une version supérieure pour être installé. Veuillez mettre à jour votre installation Windows.",
            "dotNetRequirements": "WinZip nécessite la version Microsoft .NET Framework 4.0 ou supérieure. Cliquez sur Suivant pour passer à la version .NET 4.6 et continuer l’installation de WinZip.",
            "dotNet35Requirements": "L'application nécessite .net 3.5 ou une version ultérieure. Veuillez procéder à la mise à niveau vers .net 3.5 ou une version ultérieure et relancez cette installation.",
            "ieRequirements": "L'application nécessite IE8 ou une version ultérieure. Veuillez procéder à la mise à niveau vers IE8 ou une version ultérieure et relancez cette installation.",
            "diskfullMessageText": "Il n'y a pas assez d'espace sur le disque.",
            "warningText": "Avertissement",
            "errorText": "Erreur",
            "outOfText": " sur ",
            "installLabel" : "Installation en cours...",
            "downloadingWinZip" : "Téléchargement de WinZip",
            "downloadingDotNet" : "Téléchargement de .NET Framework",
            "noNetwork" : "Aucune connexion Internet réseau ou proxy disponible.",
            "webview2InstallFail" : "L'installation de la bibliothèque Microsoft WebView2 a échoué. Veuillez éessayer d'installer WinZip à nouveau.",
            "osBitRequirements" : "Cette version de Windows ne permet pas de déployer les logiciels 64 bits."
        },
        "de": {
            "productName": "WinZip",
            "privacyPolicy": "Datenschutzerklärung",
            "termsOfUse": "Nutzungsbedingungen",
            "welcomeDescriptionTitle": "Willkommen bei WinZip",
            "welcomeDescription": "Die einfachste Art, Dateien zu komprimieren, zu schützen und weiterzugeben.",
            "agreementDescriptionTitle": "Lizenzvereinbarung",
            "agreementDescription": "Lesen Sie bitte folgende Lizenzvereinbarung durch.",
            "agreementDescriptionEULA": "WinZip registriert die Annahme dieser Bedingungen seitens der Endnutzer, wenn diese WinZip für den persönlichen Gebrauch installieren und auf diesem Bildschirm auf „Zustimmen“ klicken.",
            "endUserLicenseAgreement": "Endbenutzer-Lizenzvereinbarung",
            "agreementDescriptionBULA": "WinZip registriert die Annahme dieser Bedingungen seitens der Unternehmen, wenn diese auf diesem Bildschirm auf „Zustimmen“ klicken.",
            "businessUserLicenseAgreement": "Lizenzvereinbarung für Geschäftsbenutzer",
            "agreementFaq": "EULA & BULA FAQ",
            "analyticsDescriptionTitle": "WinZip Analytics",
            "analyticsDescription": "Bitte lesen Sie die folgende Datenschutzerklärung.",
            "analyticsHelpImproveDescription": "Helfen Sie WinZip, seine Produkte und Dienste zu verbessern, indem Sie nach der Installation anonyme Daten zur Nutzungsanalyse bereitstellen. Sie können diese Entscheidung später in den Einstellungen ändern.",
            "analyticsCollectedDescription": "Alle gesammelten Daten werden mit Techniken zum Schutz der Privatsphäre gesammelt.",
            "agreeButtonText": "Zustimmen",
            "doNotSendButtonText": "Nicht senden",
            "installingProgressBarText": "Installation",
            "installingDescriptionTitle": "Installationsstatus",
            "installDescription": "Bitte warten Sie, bis der Installationsassistent die benötigten Pakete heruntergeladen und optimiert hat.",
            "finishDescriptionTitle": "Herzlichen Dank, dass Sie WinZip installiert haben",
            "finishDescription": "Die einfachste Art, Dateien zu komprimieren, zu schützen und weiterzugeben.",
            "nextButtonText": "Weiter",
            "finishButtonText": "Beenden",
            "errorMessageText": "Während der Installation ist ein Problem aufgetreten. Bitte wenden Sie sich an den technischen Support unter Nennung des Fehlercodes %d",
            "retryMessageText": "Es wird bereits eine Installation ausgeführt. Beenden Sie die andere Installation, bevor Sie diese Installation fortsetzen.",
            "priviledgeMessageText": "Sie verfügen nicht über die erforderlichen Rechte, um diese Installation auszuführen. Melden Sie sich als Administrator an und versuchen Sie es dann erneut.",
            "osRequirements": "Für die Installation von WinZip ist eine Windows-Version ab der Version 10.0.17134 erforderlich. Bitte aktualisieren Sie Ihr Windows-Betriebssystem.",
            "dotNetRequirements": "WinZip erfordert Microsoft .NET Framework 4.0 oder neuer. Klicken Sie auf Weiter, um zu .NET 4.6 zu upgraden und mit der Installation von WinZip fortzufahren.",
            "dotNet35Requirements": "Die Anwendung erfordert .net 3.5 oder höher. Bitte führen Sie ein Upgrade auf .net 3.5 oder höher durch und führen Sie die Installation erneut aus.",
            "ieRequirements": "Die Anwendung erfordert IE8 oder höher. Bitte führen Sie ein Upgrade auf IE8 oder höher durch und führen Sie die Installation erneut aus.",
            "diskfullMessageText": "Es ist nicht genügend Speicherplatz auf dem Datenträger.",
            "warningText": "Warnung",
            "errorText": "Fehler",
            "outOfText": " von ",
            "installLabel" : "Wird installiert ...",
            "downloadingWinZip" : "Lade WinZip herunter",
            "downloadingDotNet" : "Lade .NET Framework herunter",
            "noNetwork" : "Keine Netzwerk- oder Proxy-Internetverbindung verfügbar.",
            "webview2InstallFail" : "Die Installation der Microsoft WebView2 Library ist fehlgeschlagen. Bitte versuchen Sie erneut, WinZip zu installieren.",
            "osBitRequirements" : "Diese Windows-Version unterstützt nicht die Bereitstellung von 64-Bit-Paketen."
        },
        "it": {
            "productName": "WinZip",
            "privacyPolicy": "Informativa sulla Privacy",
            "termsOfUse": "Condizioni d'uso",
            "welcomeDescriptionTitle": "Benvenuto in WinZip",
            "welcomeDescription": "Il modo più semplice di comprimere, proteggere e condividere i file.",
            "agreementDescriptionTitle": "Contratto di licenza",
            "agreementDescription": "Leggere il seguente Contratto di licenza.",
            "agreementDescriptionEULA": "WinZip registrerà l'accettazione dei seguenti termini per i singoli utenti finali, che installano WinZip per uso personale, quando si fa clic su Accetto in questa schermata.",
            "endUserLicenseAgreement": "Contratto di licenza con l'utente finale",
            "agreementDescriptionBULA": "WinZip registrerà l'accettazione dei seguenti termini per gli utenti che agiscono per un'azienda e fanno clic su Accetto in questa schermata.",
            "businessUserLicenseAgreement": "Contratto di licenza per l'utente aziendale",
            "agreementFaq": "FAQ EULA & BULA",
            "analyticsDescriptionTitle": "WinZip Analytics",
            "analyticsDescription": "Si prega di leggere la seguente Informativa sulla privacy.",
            "analyticsHelpImproveDescription": "Aiuta WinZip a migliorare i suoi prodotti e servizi fornendo dati analitici di utilizzo anonimi dal tuo WinZip dopo l'installazione. Puoi modificare questa decisione in seguito in Impostazioni.",
            "analyticsCollectedDescription": "Tutti i dati raccolti vengono raccolti utilizzando tecniche di tutela della privacy.",
            "agreeButtonText": "Accetto",
            "doNotSendButtonText": "Non inviare",
            "installingProgressBarText": "Installazione",
            "installingDescriptionTitle": "Stato dell'installazione",
            "installDescription": "Attendere che la procedura di installazione guidata scarichi e ottimizzi i pacchetti necessari.",
            "finishDescriptionTitle": "Grazie per aver installato WinZip",
            "finishDescription": "Il modo più semplice di comprimere, proteggere e condividere i file.",
            "nextButtonText": "Avanti",
            "finishButtonText": "Fine",
            "errorMessageText": "Si è verificato un problema durante l'installazione.  Contattare il Supporto tecnico e indicare il codice errore %d",
            "retryMessageText": "È in corso un'altra installazione. Completare l'installazione prima di procedere all'installazione.",
            "priviledgeMessageText": "Privilegi insufficienti per completare l'installazione. Accedere come amministratore, quindi ripetere l'installazione.",
            "osRequirements": "WinZip richiede l'installazione di Windows versione 10.0.17134 o successiva. Si prega di aggiornare l'installazione di Windows.",
            "dotNetRequirements": "WinZip richiede Microsoft .NET Framework 4.0 o versioni successive. Fare clic su Avanti per eseguire l’upgrade a .NET 4.6 e continuare a installare WinZip.",
            "dotNet35Requirements": "L'applicazione richiede .net 3.5 o versione superiore. Effettuare l'aggiornamento a .net 3.5 o versione superiore e ripetere l'installazione.",
            "ieRequirements": "L'applicazione richiede IE8 o versione superiore. Effettuare l'aggiornamento a IE8 o versione superiore e ripetere l'installazione.",
            "diskfullMessageText": "Non c'è abbastanza spazio sul disco.",
            "warningText": "Avviso",
            "errorText": "Errore",
            "outOfText": " di ",
            "installLabel" : "Installazione in corso...",
            "downloadingWinZip" : "Download di WinZip in corso",
            "downloadingDotNet" : "Download di .NET Framework in corso",
            "noNetwork" : "Nessuna rete o connessione a internet proxy disponibile.",
            "webview2InstallFail" : "L'installazione della libreria Microsoft WebView2 non è riuscita. Prova a installare di nuovo WinZip.",
            "osBitRequirements" : "Questa versione di Windows non supporta la distribuzione di pacchetti da 64 bit."
        },
        "jp": {
            "language": "Japanese",
            "productName": "WinZip",
            "privacyPolicy": "プライバシー ポリシー",
            "termsOfUse": "利用条件",
            "welcomeDescriptionTitle": "WinZip にようこそ",
            "welcomeDescription": "ファイルの圧縮、保護、共有が簡単にできます。",
            "agreementDescriptionTitle": "ライセンス契約書",
            "agreementDescription": "次のライセンス契約書をよくお読みください。",
            "agreementDescriptionEULA": "WinZip は、この画面で [同意する] をクリックすると、個人使用のために WinZip をインストールする個々のエンド ユーザーに対して、次の条件への同意を登録します。",
            "endUserLicenseAgreement": "エンド ユーザー ライセンス契約",
            "agreementDescriptionBULA": "WinZip は、ビジネスのために行動し、この画面で [同意する] をクリックしたユーザーに対して、次の条件への同意を登録します。",
            "businessUserLicenseAgreement": "ビジネス ユーザー ライセンス契約",
            "agreementFaq": "EULA & BULA FAQ",
            "analyticsDescriptionTitle": "WinZip アナリティクス",
            "analyticsDescription": "次のプライバシー ポリシーをお読みください。",
            "analyticsHelpImproveDescription": "インストール後に WinZip から匿名の使用分析データを提供することで、WinZip が製品とサービスを改善するのに役立ちます。この決定は、後で [設定] で変更できます。",
            "analyticsCollectedDescription": "収集されたすべてのデータは、プライバシー保護技術を使用して収集されます。",
            "agreeButtonText": "同意する",
            "doNotSendButtonText": "送信しない",
            "installingProgressBarText": "インストール",
            "installingDescriptionTitle": "インストール状況",
            "installDescription": "インストーラ ウィザードが必要なパッケージをダウンロードし最適化しています。しばらくお待ちください。",
            "finishDescriptionTitle": "WinZip をインストールいただきありがとうございます",
            "finishDescription": "ファイルの圧縮、保護、共有が簡単にできます。",
            "nextButtonText": "次へ",
            "finishButtonText": "終了",
            "errorMessageText": "インストール中に問題が発生しました。テクニカル サポートに連絡し、エラー コード %d をお伝えください。",
            "retryMessageText": "別のインストールが実行されています。現行のインストールが完了してから本インストールを開始してください。",
            "priviledgeMessageText": "このインストールを行う権限がありません。管理者としてログオンし、再試行してください。",
            "osRequirements": "WinZip をインストールするには、Windows バージョン 10.0.17134 以降が必要です。 Windows インストールをアップグレードしてください。",
            "dotNetRequirements": "WinZipにはMicrosoft .NET Framework 4.0以上が必要です。次へをクリックして.NET 4.6へアップグレードし、続いてWinZipをインストールする。",
            "dotNet35Requirements": "本アプリケーションには .net 3.5 以上のバージョンが必要です。.net 3.5 以上にアップグレードしてから、インストールを再試行してください。",
            "ieRequirements": "本アプリケーションには IE8 以上のバージョンが必要です。IE8 以上にアップグレードしてから、インストールを再試行してください。",
            "diskfullMessageText": "ディスクに十分な空き領域がありません。",
            "warningText": "警告",
            "errorText": "エラー",
            "outOfText": " 中 ",
            "installLabel" : "インストールしています...",
            "downloadingWinZip" : "WinZipのダウンロード",
            "downloadingDotNet" : ".NET Frameworkのダウンロード",
            "noNetwork" : "利用可能なネットワークまたはプロキシ インターネット接続がありません。",
            "webview2InstallFail" : "Microsoft WebView2 ライブラリのインストールに失敗しました。 WinZip を再度インストールしてください。",
            "osBitRequirements" : "このバージョンの Windows では 64 ビット パッケージの展開はサポートされていません。"
        },
        "es": {
            "productName": "WinZip",
            "privacyPolicy": "Declaración de privacidad",
            "termsOfUse": "Condiciones de uso",
            "welcomeDescriptionTitle": "Bienvenido a WinZip",
            "welcomeDescription": "La forma más fácil de comprimir, proteger y compartir sus archivos.",
            "agreementDescriptionTitle": "Contrato de licencia",
            "agreementDescription": "Lea el siguiente Contrato de licencia.",
            "agreementDescriptionEULA": "WinZip registrará la aceptación de los siguientes términos para usuarios finales individuales que instalen WinZip para uso personal al hacer clic en Aceptar en esta pantalla.",
            "endUserLicenseAgreement": "Acuerdo de licencia de usuario final",
            "agreementDescriptionBULA": "WinZip registrará la aceptación de los siguientes términos para los usuarios que actúen en nombre de una empresa y hagan clic en aceptar en esta pantalla.",
            "businessUserLicenseAgreement": "Acuerdo de Licencia de Usuario Comercial",
            "agreementFaq": "Preguntas frecuentes sobre EULA y BULA",
            "analyticsDescriptionTitle": "Análisis WinZip",
            "analyticsDescription": "Lea la siguiente Política de privacidad.",
            "analyticsHelpImproveDescription": "Ayuda a WinZip a mejorar sus productos y servicios proporcionando datos analíticos de uso anónimos de tu WinZip después de la instalación. Puedes cambiar esta decisión más tarde en Configuración.",
            "analyticsCollectedDescription": "Todos los datos recopilados se recopilan mediante técnicas de preservación de la privacidad.",
            "agreeButtonText": "Acepto",
            "doNotSendButtonText": "No enviar",
            "installingProgressBarText": "Instalación",
            "installingDescriptionTitle": "Estado de la instalación",
            "installDescription": "Espere mientras el asistente de instalación descarga y optimiza los paquetes necesarios.",
            "finishDescriptionTitle": "Gracias por instalar WinZip",
            "finishDescription": "La forma más fácil de comprimir, proteger y compartir sus archivos.",
            "nextButtonText": "Siguiente",
            "finishButtonText": "Finalizar",
            "errorMessageText": "Se produjo un problema durante la instalación. Póngase en contacto con Asistencia técnica y mencione el código de error %d",
            "retryMessageText": "Ya está en curso otra instalación. Complete esa instalación antes de continuar con esta instalación.",
            "priviledgeMessageText": "No dispone de privilegios suficientes para completar esta instalación. Inicie sesión como administrador y vuelva a intentar realizar la instalación.",
            "osRequirements": "Winzip require de una versión de Windows 10.0.17134 o superior para instalarse. Por favor, actualiza tu Windows.",
            "dotNetRequirements": "WinZip requiere Microsoft.NET Framework 4.0 o superior. Haz clic en Siguiente para actualizar a la versión .NET 4.6 y sigue instalando WinZip.",
            "dotNet35Requirements": "La aplicación requiere .net 3.5 o posterior. Actualice a .net 3.5 o posterior y vuelva a intentar realizar la instalación.",
            "ieRequirements": "La aplicación requiere IE8 o posterior. Actualice a IE8 o posterior y vuelva a intentar realizar la instalación.",
            "diskfullMessageText": "No hay suficiente espacio en el disco.",
            "warningText": "Advertencia",
            "errorText": "Error",
            "outOfText": " de ",
            "installLabel" : "Instalando...",
            "downloadingWinZip" : "Descargando WinZip",
            "downloadingDotNet" : "Descargando .NET Framework",
            "noNetwork" : "No hay disponible ninguna conexión a la red o a un proxy de Internet.",
            "webview2InstallFail" : "La instalación de la galería de Microsoft WebView2 ha fallado. Por favor, prueba a instalar WinZip de nuevo.",
            "osBitRequirements" : "Esta versión de Windows no admite la distribución de paquetes de 64 bits."
        },
        "zh": {
            "productName": "WinZip",
            "privacyPolicy": "隐私声明",
            "termsOfUse": "使用条款",
            "welcomeDescriptionTitle": "欢迎使用 WinZip",
            "welcomeDescription": "以最简单的方法压缩、保护和共享您的文件。",
            "agreementDescriptionTitle": "许可协议",
            "agreementDescription": "请阅读以下许可协议。",
            "agreementDescriptionEULA": "当点击此屏幕上的同意时，WinZip 将为安装 WinZip 供个人使用的个人最终用户注册接受以下条款。",
            "endUserLicenseAgreement": "最终用户许可协议",
            "agreementDescriptionBULA": "WinZip 将为代表企业的用户注册接受以下条款并在此屏幕上单击同意。",
            "businessUserLicenseAgreement": "商业用户许可协议",
            "agreementFaq": "EULA & BULA 常见问题解答",
            "analyticsDescriptionTitle": "WinZip 分析",
            "analyticsDescription": "请阅读以下隐私政策。",
            "analyticsHelpImproveDescription": "安装后从您的 WinZip 提供匿名使用分析数据，帮助 WinZip 改进其产品和服务。您可以稍后在设置中更改此决定。",
            "analyticsCollectedDescription": "所有收集的数据都是使用隐私保护技术收集的。",
            "agreeButtonText": "同意",
            "doNotSendButtonText": "不发送",
            "installingProgressBarText": "正在安装",
            "installingDescriptionTitle": "安装状态",
            "installDescription": "请稍候，等待下载安装程序向导并优化所需的程序包。",
            "finishDescriptionTitle": "感谢您安装 WinZip",
            "finishDescription": "最简便的文件压缩、保护、分享方式。",
            "nextButtonText": "下一步",
            "finishButtonText": "完成",
            "errorMessageText": "我们在安装过程中遇到一个问题。请联系技术支持并告知错误代码 %d",
            "retryMessageText": "另一个安装过程已在进行中。请在进行此安装前，完成前述安装。",
            "priviledgeMessageText": "您不具备完成此安装的权限。请以管理员身份登录，然后重试此安装。",
            "osRequirements": "WinZip 需要 Windows 版本 10.0.17134 或更高版本才能安装。请升级您的 Windows 安装。",
            "dotNetRequirements": "WinZip 需要 Microsoft .NET Framework 4.0 或更高版本。单击“下一步”升级至 .NET 4.6 并继续安装 WinZip。",
            "dotNet35Requirements": "应用程序需要 .net 3.5 或更高版本。请升级到 .net 3.5 或更高版本，然后重试此安装。",
            "ieRequirements": "应用程序需要 IE8 或更高版本。请升级到 IE8 或更高版本，然后重试此安装。",
            "diskfullMessageText": "在磁盘上没有足够的空间。",
            "warningText": "警告",
            "errorText": "错误",
            "outOfText": " 更新，共 ",
            "installLabel" : "安裝中...",
            "downloadingWinZip" : "下载 WinZip",
            "downloadingDotNet" : "下载 .NET Framework",
            "noNetwork" : "没有可用的 Internet 连接或代理服务器无效。",
            "webview2InstallFail" : "Microsoft WebView2 库的安装失败。请再次尝试安装 WinZip。",
            "osBitRequirements" : "此版本 Windows 不支持部署 64 位软件包。"
        },
        "pt": {
            "language": "Portuguese",
            "productName": "WinZip",
            "privacyPolicy": "Declaração de Privacidade",
            "termsOfUse": "Termos de uso",
            "welcomeDescriptionTitle": "Bem-vindo(a) ao WinZip",
            "welcomeDescription": "A forma mais fácil de compactar, proteger e compartilhar seus arquivos.",
            "agreementDescriptionTitle": "Contrato de licença",
            "agreementDescription": "Leia o Contrato de licença a seguir.",
            "agreementDescriptionEULA": "O WinZip registrará a aceitação dos seguintes termos para usuários finais individuais, que instalarem o WinZip para uso pessoal, ao clicar em concordar nesta tela.",
            "endUserLicenseAgreement": "Contrato de Licença de Usuário Final",
            "agreementDescriptionBULA": "O WinZip registrará a aceitação dos seguintes termos para usuários, que estão atuando para uma empresa e clique em concordar nesta tela.",
            "businessUserLicenseAgreement": "Contrato de Licença de Usuário Comercial",
            "agreementFaq": "Perguntas frequentes sobre EULA e BULA",
            "analyticsDescriptionTitle": "Análise WinZip",
            "analyticsDescription": "Por favor, leia a seguinte Política de Privacidade.",
            "analyticsHelpImproveDescription": "Ajude o WinZip a melhorar seus produtos e serviços fornecendo dados anônimos de análise de uso do seu WinZip após a instalação. Você pode alterar essa decisão posteriormente em Configurações.",
            "analyticsCollectedDescription": "Todos os dados coletados são coletados usando técnicas de preservação de privacidade.",
            "agreeButtonText": "Concordo",
            "doNotSendButtonText": "Não enviar",
            "installingProgressBarText": "Instalando",
            "installingDescriptionTitle": "Status da instalação",
            "installDescription": "Aguarde enquanto o assistente de instalação baixa e otimiza os pacotes necessários.",
            "finishDescriptionTitle": "Obrigado por instalar o WinZip",
            "finishDescription": "A forma mais fácil de compactar, proteger e compartilhar seus arquivos.",
            "nextButtonText": "Próximo",
            "finishButtonText": "Concluir",
            "errorMessageText": "Encontramos um problema durante a instalação.  Entre em contato com o suporte técnico e mencione o código de erro %d",
            "retryMessageText": "Outra instalação já está em andamento. Conclua essa instalação antes de continuar com esta instalação.",
            "priviledgeMessageText": "Você não dispõe de privilégios suficientes para concluir esta instalação. Faça logon como administrador e tente realizar a instalação novamente.",
            "osRequirements": "WinZip requer Windows versão 10.0.17134 ou superior para instalar. Atualize a instalação do Windows.",
            "dotNetRequirements": "O WinZip requer Microsoft .NET Framework 4.0 ou superior. Clique Avançar para atualizar em .NET 4.6 e continue a instalar o WinZip.",
            "dotNet35Requirements": "O aplicativo requer o .net 3.5 ou posterior. Atualize para o .net 3.5 ou posterior e tente realizar a instalação novamente.",
            "ieRequirements": "O aplicativo requer o IE8 ou posterior. Atualize para o IE8 ou posterior e tente realizar a instalação novamente.",
            "diskfullMessageText": "Não há espaço suficiente no disco.",
            "warningText": "Aviso",
            "errorText": "Erro",
            "outOfText": " fora de ",
            "installLabel" : "installing...",
            "downloadingWinZip" : "Fazendo o download do WinZip",
            "downloadingDotNet" : "Fazendo o download do .NET Framework",
            "noNetwork" : "Nenhuma rede ou conexão com internet disponível.",
            "webview2InstallFail" : "A instalação da biblioteca Microsoft WebView2 falhou. Tente instalar o WinZip novamente.",
            "osBitRequirements" : "Esta versão do Windows não suporta a implantação de pacotes de 64 bits."
        },
        "nl": {
            "language": "Dutch",
            "productName": "WinZip",
            "privacyPolicy": "Privacystatement",
            "termsOfUse": "Gebruiksvoorwaarden",
            "welcomeDescriptionTitle": "Welkom bij WinZip",
            "welcomeDescription": "De eenvoudigste manier om bestanden in te pakken, te beveiligen en delen.",
            "agreementDescriptionTitle": "Licentieovereenkomst",
            "agreementDescription": "Lees de volgende licentieovereenkomst.",
            "agreementDescriptionEULA": "WinZip zal voor eindgebruikers, die WinZip voor persoonlijk gebruik installeren, de aanvaarding van de volgende voorwaarden registreren door op akkoord te klikken.",
            "endUserLicenseAgreement": "Licentieovereenkomst voor eindgebruikers",
            "agreementDescriptionBULA": "WinZip zal voor eindgebruikers, die WinZip voor zakelijk gebruik installeren, de aanvaarding van de volgende voorwaarden registreren door op akkoord te klikken.",
            "businessUserLicenseAgreement": "Licentieovereenkomst voor zakelijke gebruikers",
            "agreementFaq": "Veelgestelde vragen over licentieovereenkomsten ",
            "analyticsDescriptionTitle": "WinZip Analytics",
            "analyticsDescription": "Lees het volgende privacybeleid.",
            "analyticsHelpImproveDescription": "Help WinZip met het verbeteren van producten en diensten door anonieme WinZip-gebruiksgegevens te delen. U kunt dit later aanpassen in de instellingen.",
            "analyticsCollectedDescription": "Alle gegevens worden verzameld met behulp van privacybeschermende technieken. ",
            "agreeButtonText": "Akkoord",
            "doNotSendButtonText": "Geen gegevens delen",
            "installingProgressBarText": "Installatie",
            "installingDescriptionTitle": "Installatiestatus",
            "installDescription": "Een ogenblik geduld. De installatiewizard downloadt en optimaliseert de vereiste pakketten.",
            "finishDescriptionTitle": "Dank u voor het installeren van WinZip",
            "finishDescription": "De eenvoudigste manier om bestanden in te pakken, te beveiligen en delen.",
            "nextButtonText": "Volgende",
            "finishButtonText": "Voltooien",
            "errorMessageText": "Er is een probleem opgetreden tijdens de installatie.  Neem contact op met de Technische ondersteuning en vermeld foutcode %d",
            "retryMessageText": "Er wordt al een andere installatie uitgevoerd. Voltooi de betreffende installatie voordat u verdergaat met deze installatie.",
            "priviledgeMessageText": "U bent niet gemachtigd om deze installatie te voltooien. Meld u aan als beheerder en probeer de installatie opnieuw uit te voeren.",
            "osRequirements": "WinZip vereist Windows versie 10.0.17134 of hoger. Upgrade uw Windows-installatie.",
            "dotNetRequirements": "WinZip vereist Microsoft. NET Framework 4.0 of hoger. Klik volgende om te upgraden naar .NET en ga door met het installeren van WinZip.",
            "dotNet35Requirements": "Voor de toepassing is .net 3.5 of hoger vereist. Voer een upgrade uit naar .net 3.5 of hoger en probeer de installatie opnieuw uit te voeren.",
            "ieRequirements": "Voor de toepassing is IE8 of hoger vereist. Voer een upgrade uit naar IE8 of hoger en probeer de installatie opnieuw uit te voeren.",
            "diskfullMessageText": "Er is niet genoeg ruimte op de schijf.",
            "warningText": "Waarschuwing",
            "errorText": "Fout",
            "outOfText": " van ",
            "installLabel" : "Installatie aan de gang...",
            "downloadingWinZip" : "Het downloaden van WinZip",
            "downloadingDotNet" : "Het downloaden van .NET Framework",
            "noNetwork" : "Geen netwerk- of proxy-internetverbinding beschikbaar.",
            "webview2InstallFail" : "De installatie van de Microsoft WebView2-library is mislukt. Probeer WinZip opnieuw te installeren.",
            "osBitRequirements" : "Deze versie van Windows biedt geen ondersteuning voor het implementeren van 64-bits pakketten."
        }
    }  
}